### ISSUE TITLE
Add workflows that are not directly using `pathogen-repo-build` 

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/status#12]
## Context
Prompted by https://github.com/nextstrain/zika/pull/55#issuecomment-2070966728

We want to monitor GH Action workflows using the `pathogen-repo-build` reusable workflow and we are currently filtering for them with 

https://github.com/nextstrain/status/blob/d744ff7226ca38d1f73f1b65c7b8d44517a5a4dd/pathogen-workflows.sql#L87-L88

However, this does not include workflows that are nesting reusable workflows, such as the current [zika ingest-to-phylo.yaml workflow](https://github.com/nextstrain/zika/blob/fe37759afd63c2ec5772c3094a84a52b877e70e5/.github/workflows/ingest-to-phylogenetic.yaml). 

## Possible solutions

1. We could add another proxy for filtering if we use a stable pattern across pathogen repos. e.g filter for path `ingest-to-phylogenetic.yaml` 
2. We could traverse the nested workflows to check if any of them are using the `pathogen-repo-build` workflow. (GH Action currently allows four levels of [nested reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows#nesting-reusable-workflows))

**Comment by joverlee521** [comment]
Ah right, just remembered this issue since I changed avian flu GH Action workflows in https://github.com/nextstrain/avian-flu/pull/71 but the name is `ingest-to-phylogenetic-ncbi.yaml` instead of `ingest-to-phylogenetic.yaml`. 

I'm going to add a separate check for the avian-flu workflow, but other pathogens that _only_ use NCBI data should continue to follow the generic `ingest-to-phylogenetic.yaml` naming.

**Comment by joverlee521** [comment]
Or maybe just update exact match to pattern match

```diff
diff --git a/pathogen-workflows.sql b/pathogen-workflows.sql
index d68d368..cf23d33 100644
--- a/pathogen-workflows.sql
+++ b/pathogen-workflows.sql
@@ -93,7 +93,7 @@ workflow as materialized (
                  *
                  * <https://github.com/nextstrain/status/issues/12>
                  */
-                or path = '.github/workflows/ingest-to-phylogenetic.yaml')
+                or path like '.github/workflows/ingest-to-phylogenetic%.yaml')
         and name != 'CI'
 ),
```

**Comment by genehack** [comment]
@joverlee521 it looks like, reviewing the above, that the work here is done and this issue can be closed?

**Comment by joverlee521** [comment]
Ah yeah, I'll consider https://github.com/nextstrain/status/pull/24 good enough. We can re-open this if there are other cases not supported.
