### ISSUE TITLE
pathogen-workflows: Duration calculation is using wrong timestamps when multiple attempts are present

### ISSUE THREAD

**Issue by tsibley** [nextstrain/status#18]
### Current Behavior
![image](https://github.com/nextstrain/status/assets/79913/45d075d8-acb9-472f-8678-4558194e6f0e)

Normal time is ~5min. I haven't checked but am guessing that [attempt 1](https://github.com/nextstrain/forecasts-ncov/actions/runs/9396520238/attempts/1)'s start time got subtracted from [attempt 2](https://github.com/nextstrain/forecasts-ncov/actions/runs/9396520238/attempts/2)'s end time.

### Expected behavior
Calculation is limited to latest attempt.

**Comment by tsibley** [comment]
Noticed this again today with:

1. https://github.com/nextstrain/mpox/actions/runs/12331704541/attempts/1
2. https://github.com/nextstrain/mpox/actions/runs/12331704541/attempts/2

Buggy code is:

https://github.com/nextstrain/status/blob/60bee3da60bc9c5cc88ea1242e907a2b9ef0974b/pathogen-workflows.sql#L111-L114

This works for a run with a single attempt, but for a multi-attempt run, `created_at` stays at its original value (the creation time of the first attempt), and so the duration is wrong. (If you fetch a _specific attempt_ via GitHub's API, `created_at` _is_ tracked separately per attempt there, as you'd hope.)

Steampipe unfortunately doesn't expose attempt info, so we can't (super quickly) take into account attempt info.

The overall run record does include `run_started_at`, which updates with each subsequent attempt, but that means our durations will no longer include queue time, which was an intentional choice originally.

**Comment by tsibley** [comment]
Layout is based on creation, and currently the details box shows a creation timestamp and a duration based on that creation timestamp. This has a nice property that the creation + duration gives you when the run ended. If we switch to duration based on run start time (and thus maybe for a re-run attempt), we lose that property and creation time becomes more disconnected from practical usefulness.

I think ideally we treat re-runs like totally separate runs. That simplifies the data to present on the page and though it loses linkage of runs, that's fine for our usage with mostly scheduled runs. (You can imagine how it wouldn't be fine for something like re-runs of a workflow that's processing say a software release.) Steampipe makes getting run attempt info slightly difficult as-is currently (but it's possible).

Alternatively, we can start showing run start time in addition to creation time and try to present that nuance of the data clearly.

**Comment by joverlee521** [comment]
> Alternatively, we can start showing run start time in addition to creation time and try to present that nuance of the data clearly.

I vote for the inclusion of both times. Even if we don't have the run attempt info, it's useful to know the latest run's duration.

**Comment by tsibley** [comment]
I have inclusion of all attempts working locally. :-) Need to get it cleaned up and pushed, but it works well, and I've managed to make the queries faster to boot too.

**Comment by tsibley** [comment]
WIP is pushed now as `trs/reruns`: https://github.com/nextstrain/status/compare/trs/reruns

It works great, but I want to clean up the `wip!` commits for readability and loop back at the SQL to see if I can simplify things a bit more.

**Comment by tsibley** [comment]
Fixed by https://github.com/nextstrain/status/pull/34.
