### ISSUE TITLE
Show details card on hover vs click?

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/status#21]
### Context

I only noticed that there was a detailed tooltip available on click after quite some time looking at the status page.

Making the details show up on hover instead of requiring click would make that functionality more discoverable - at the cost of causing "false positive" tooltip popups that are not intentional.

Showing on hover would reduce the time it takes to quickly scan build run and start times.

I'm talking about this card/tooltip that appears currently only on click:
<img width="908" alt="image" src="https://github.com/nextstrain/status/assets/25161793/6bc60f75-17fd-4e58-913f-472bf701e1fb">

**Comment by tsibley** [comment]
There would be so many hover targets that I think it would be twitchy and overwhelming. I really dislike interfaces like that.

The ability to click is (if subtly) indicated by the change of cursor when you mouse over a run. There is certainly an element of discoverability we could improve upon, but it's also a one-time cost in the short learning curve that doesn't feel too onerous.

> Showing on hover would reduce the time it takes to quickly scan build run and start times.

Once you have a details box open, you can use h/j/k/l to move focus around, thus letting you quickly scan thru dates or other details of a series of runs.

**Comment by genehack** [comment]
@tsibley this sounds like "close as not planned", based on your comment?
