### ISSUE TITLE
Finalize prototype 

### ISSUE THREAD

**Issue by genehack** [nextstrain/status#25]
Extracted from [Q3 planning meeting](https://docs.google.com/document/d/150k8VU2q5IXYU3a2_g4mLLJGCh-A5AJNguppu9dCU-A/edit) notes.

Meta-issue for tracking remaining work involved in getting this prototype "done" and making it available at (e.g.) status.nextstrain.org. @genehack to build a more detailed roadmap.

**Comment by tsibley** [comment]
I've made the site available at https://status.nextstrain.org.

As far as I can tell, this status dashboard is "done enough". We're using it, it gets small tweaks/improvements over time as we desire, and we have the ability to add more status pages using the same framework over time. If there's more that's desired, let's get it written out so we can do it. :-)
