### ISSUE TITLE
CI: steampipe hangs on schemas 

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/status#5]
I've gotten alerts of the CI failing after https://github.com/nextstrain/status/pull/4.
Seems like the CI jobs intermittently hangs on steampipe schemas:

- [March 08, 2024, 1:43AM PST](https://github.com/nextstrain/status/actions/runs/8201501435)
- [March 09, 2024, 4:51AM PST](https://github.com/nextstrain/status/actions/runs/8214670596)
- [March 12, 2024, 10:29PM PDT](https://github.com/nextstrain/status/actions/runs/8244055529)
- [March 12, 2024, 11:26AM PDT](https://github.com/nextstrain/status/actions/runs/8253964760) - I noticed this hanging, so I manually cancelled the workflow. 

They all had similar logs that show `Waiting for Steampipe plugin schemas to be ready…` until the job times out at GitHub Action's 6hr limit. 
```
mkdir -p build
./steampipe-psql --quiet --no-psqlrc --no-align --tuples-only --set=ON_ERROR_STOP= < pathogen-workflows.sql > build/pathogen-workflows.json
Using PGHOST=localhost PGPORT=9193 PGUSER=steampipe PGDATABASE=steampipe
Steampipe Postgres service not available; starting it…
Steampipe service is running:

Database:

  Host(s):            127.0.0.1, ::1, localhost
  Port:               9193
  Database:           steampipe
  User:               steampipe
  Password:           ********* [use --show-password to reveal]
  Connection string:  postgres://steampipe@127.0.0.1:9193/steampipe

Managing the Steampipe service:

  # Get status of the service
  steampipe service status

  # View database password for connecting from another machine
  steampipe service status --show-password

  # Restart the service
  steampipe service restart

  # Stop the service
  steampipe service stop

Waiting for Steampipe plugin schemas to be ready…
Waiting for Steampipe plugin schemas to be ready…
Waiting for Steampipe plugin schemas to be ready…
Waiting for Steampipe plugin schemas to be ready…
Waiting for Steampipe plugin schemas to be ready…
(...)
Error: The operation was canceled.
```

**Comment by joverlee521** [comment]
Haven't seen this issue since a [run on April 2](https://github.com/nextstrain/status/actions/runs/8524957523), maybe it's no longer an issue 🤞

**Comment by joverlee521** [comment]
Damn, I might have jinxed it ([hanging workflow](https://github.com/nextstrain/status/actions/runs/8745602905)). I shouldn't have said anything.

**Comment by tsibley** [comment]
Odd. As a workaround for now, we could impose a workflow/job timeout of 10 minutes? 20 minutes? or similar and not let things hang for 6 hours.

**Comment by tsibley** [comment]
Closing as this hasn't been observed for a while now and we have the workaround of a GitHub-level workflow timeout thanks to #11.
